CREATE TABLE IF NOT EXISTS shortened_url (
    id VARCHAR(5) PRIMARY KEY,
    full_url VARCHAR NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ttl INTERVAL DEFAULT '90 days'
);